name: Python application test with Github Actions

on:
  # push:
  #   branches: ["master"]
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.9.18
      uses: actions/setup-python@main
      with:
        python-version: 3.9.18
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
